<?php
/**
 * Display comments in admin
 *
 * @author g.raoult@gmail.com
 */
    $this->title = 'Administration - Commentaires';
    $this->headTitle($this->title);
    $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery.confirm/jquery.confirm.css');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jquery.confirm/jquery.confirm.js', $type = 'text/javascript');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jquery.simpletip-1.3.1.min.js', $type = 'text/javascript');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/admin_comments.js', $type = 'text/javascript');
    echo $this->inlineScript();

?>

<div id="dashboard_content">
    <?php
    if($this->message != '') echo '<p>',$this->message,'</p>';
    echo '<h2 class="titre_form_article"><img src="'.$this->baseUrl().'/images/titre_gerer_commentaires.png" alt="Gérer les commentaires"/></h2>';
    ?>
    <h2 class="titre_cat_admin"></h2>
    <table id="table_comments">
        <thead>
            <tr>
                <td>Auteur</td>
                <td>Commentaire</td>
                <td>Article</td>
                 <td></td>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($this->comments as $comment):
            ?>
                <tr>
                    <?php echo '<td class="info_author"><span class="comment_author">'.$comment->comment_author.'</span>
                        <span class="comment_ip">'.$comment->comment_ip.'</span>
                        <span class="comment_email">'.$comment->comment_email.'</span>
                        <span class="comment_website"><a href="'.$comment->comment_web.'">'.$comment->comment_web.'</span></td>' ?>
                    <?php echo '<td class="info_content"><span class="comment_content">'.$comment->comment_content.'</span>
                        <span class="comment_date">Posté le '.date("j/m/y G:i:s", strtotime($comment->comment_date)).'</span>
                        </td>' ?>
                    <?php echo '<td class="info_article"><span class="comment_article">'.$comment->comment_post.'</span></td>' ?>
                    <?php echo '<td class="info_action"><span class="comment_action"><a class="btn_supprimer" href="delete-comment/'.$comment->comment_id.'"><img src="'.$this->baseUrl().'/images/delete.png" alt="Supprimer"/></a></span></td>' ?>
                </tr>
            <?php
                endforeach;
            ?>
        </tbody>
    </table>
</div>