<?php

/**
 * Display about page
 *
 * @author g.raoult@gmail.com
 */

$this->title = 'En cours d\'assemblage';
$this->headTitle($this->title);

?>
<section>
    <article>
        <section class="article_content">
			<h1>A propos de...</h1><br/>
			<h2>...l'auteur</h2>
            <!--<img src="<?php echo $this->BaseUrl() ?>/images/illus_about.jpg" alt="Auteur"/>-->
            <p>Je travaille actuellement au service informatique du CarifOref 
			Midi-Pyrénées à Toulouse, une association régionale oeuvrant
			pour l'emploi et la formation professionnelle. Notre mission est 
			d'informer les diférents publics auprès des possibilités et des mutations 
			en matière d'éducation, d'orientation et de professionnalisation. 
			Cela inclu le traitement et la mise à disposition de nombreuses données
			sur des supports divers et variés.
			</p>
			<p>
				J'aime tout particulièrement :
			</p>
				<ul>
					<li>Voyager et découvrir des modes de vie différents</li>
					<li>Voyager et découvrir des modes de vie différents</li>
					<li>Voyager et découvrir des modes de vie différents</li>
				</ul>
			<br/>
        </section>
        <section class="article_content">
			<h2>...ce blog</h2>
            <!--<img src="<?php echo $this->BaseUrl() ?>/images/illus_about.jpg" alt="Auteur"/>-->
            <p>Bien que j'apprécie beaucoup Wordpress et ses possibilités quasi infinies, 
			il est souvent plus intéressant de réaliser ses propres outils afin de mieux appréhender
			par la suite ceux des autres. C'est le but que j'ai cherché à atteindre en 
			réalisant ce petit CMS sous Zend durant mes études, dans un cadre où la seule contrainte 
			était de mettre en ligne un blog.<p>
			</p>
			Il est certes loin d'être finalisé et de répondre à tous les critères requis pour une 
			plus grande diffusion mais il satisfait mes quelques exigences et m'a avant tout permis
			d'en apprendre beaucoup dans des domaines variés. 
			<p>Son code source est disponible sur GitHub à l'adresse suivante :
			<a href="http://github.com">Github</a>.
			</p>
        </section>
    </article>
</section>