<?php

/**
 * Display contact page
 *
 * @author g.raoult@gmail.com
 */

$this->title = 'En cours d\'assemblage';
$this->headTitle($this->title);

?>
<section>
    <article>
        <header>
            <h1>Contact</h1>
        </header>
        <section class="article_content">
            <p>
            This is one of those technology and legal stories that is hard 
            to believe in this day and age. If you are in Illinois, you better be 
            careful where you point your cameraphone or voice recorder.
            </p>
        </section>
    </article>
    <section>
    <?php
        if($this->message) echo '<p class="form_state" id="form_success">',$this->message,'</p>';
        if($this->erreur != '') echo '<p class="form_state" id="form_error">',$this->erreur,'</p>';
        echo $this->formContact;
    ?>
    </section>
	<!--<section class="article_content">
			<h3>Me joindre également sur :</h3>
            <ul>
				<li>Twitter : <a href="http://www.twitter.com/icanhasnickname">@icanhasnickname</a></li>
				<li><a href="http://liandri.fr/zeblog/images/linked-in_logo.png">LinkedIn</a></li>
			</ul>
	</section>-->
</section>